version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: pasaporte_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pasaporte_db
      POSTGRES_USER: pasaporte_user
      POSTGRES_PASSWORD: pasaporte_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pasaporte_network

  # pgAdmin para administración de base de datos
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pasaporte_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pasaporte.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - pasaporte_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pasaporte_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://pasaporte_user:pasaporte_password@postgres:5432/pasaporte_db
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - pasaporte_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  pasaporte_network:
    driver: bridge
