name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts
          fi

      - name: Package repository
        run: |
          # create tarball excluding VCS and node_modules to keep size small
          tar --exclude='.git' --exclude='node_modules' -czf repo.tar.gz .

      - name: Create deploy env file from secrets
        run: |
          # If you prefer, set DEPLOY_ENV secret with full env file content.
          if [ -n "${{ secrets.DEPLOY_ENV }}" ]; then
            echo "${{ secrets.DEPLOY_ENV }}" > deploy.env
          else
            echo "# generated by workflow" > deploy.env
            echo "NODE_ENV=${{ secrets.NODE_ENV || 'production' }}" >> deploy.env
            echo "DB_HOST=${{ secrets.DB_HOST || 'postgres' }}" >> deploy.env
            echo "DB_PORT=${{ secrets.DB_PORT || '5432' }}" >> deploy.env
            echo "DB_NAME=${{ secrets.DB_NAME || 'pasaporte_db' }}" >> deploy.env
            echo "DB_USER=${{ secrets.DB_USER || 'pasaporte_user' }}" >> deploy.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD || '' }}" >> deploy.env
          fi

      - name: Upload repo and scripts to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.SSH_PORT || '22' }}
        run: |
          scp -P ${VPS_PORT} -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa repo.tar.gz ${VPS_USER}@${VPS_HOST}:/tmp/repo.tar.gz
          scp -P ${VPS_PORT} -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa deploy.env ${VPS_USER}@${VPS_HOST}:/tmp/deploy.env
          scp -P ${VPS_PORT} -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa .github/scripts/remote-deploy.sh ${VPS_USER}@${VPS_HOST}:/tmp/remote-deploy.sh

      - name: Execute remote deploy on VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.SSH_PORT || '22' }}
        run: |
          ssh -p ${VPS_PORT} -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ${VPS_USER}@${VPS_HOST} 'bash /tmp/remote-deploy.sh /tmp/repo.tar.gz /tmp/deploy.env'
